MiniTrello/Board/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("boards/index/", views.boardList, name="board-list"),
    path("boards/add-board/", views.createBoard, name="create-board"),
    path("boards/<int:board_id>/update-board/", views.updateBoard, name="update-board"),
    path("boards/<int:board_id>/delete-board/", views.deleteBoard, name="delete-board"),
    path("boards/<int:board_id>/", views.boardIndex, name="board-index"),
    # Card urls
    path(
        "boards/<int:board_id>/create-card/<int:section_id>/",
        views.createCard,
        name="create-card",
    ),
    path(
        "boards/<int:board_id>/update-card/<int:card_id>/",
        views.updateCard,
        name="update-card",
    ),
    path(
        "boards/<int:board_id>/delete-card/<int:card_id>/",
        views.deleteCard,
        name="delete-card",
    ),
    # Section urls
    path(
        "boards/<int:board_id>/create-section/",
        views.createSection,
        name="create-section",
    ),
    path(
        "boards/<int:board_id>/update-section/<int:section_id>",
        views.updateSection,
        name="update-section",
    ),
    path(
        "boards/<int:board_id>/delete-section/<int:section_id>/",
        views.deleteSection,
        name="delete-section",
    ),
    path("boards/<int:board_id>/tags/", views.tagList, name="tag-list"),
    path("boards/<int:board_id>/tags/create", views.createTag, name="create-tag"),
    path(
        "boards/<int:board_id>/tags/delete/<int:tag_id>",
        views.deleteTag,
        name="delete-tag",
    ),
    path("populate/", views.populateDB, name="populate-db"),
]

MiniTrello/MiniTrello/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("Board.urls")),
    path("", include("User.urls")),
]

MiniTrello/User/urls.py
from django.urls import path
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    path("", RedirectView.as_view(pattern_name="home", permanent=False)),
    path("home/", views.homePage, name="home"),
    path("about/", views.aboutPage, name="about"),
    path("register/", views.userRegister, name="user-register"),
    path("activate/<uidb64>/<token>/", views.activate, name="activate"),
    path(
        "change-password/<uidb64>/<token>/",
        views.password_change,
        name="change-password",
    ),
    path("reset-password/", views.resetPassword, name="reset-password"),
    path("login/", views.userLogin, name="user-login"),
    path("logout/", views.userLogout, name="user-logout"),
]

MiniTrello/Board/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings


MAX_TITLE_LEN = 64
USER = settings.AUTH_USER_MODEL


class Board(models.Model):
    owner = models.ForeignKey(USER, on_delete=models.CASCADE, related_name="owner")
    members = models.ManyToManyField(USER, blank=True, related_name="members")
    title = models.CharField(max_length=MAX_TITLE_LEN, blank=False, null=False)
    description = models.TextField(blank=True, null=False)
    # TODO: add section_limit field
    # === non-editable ===
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["id"]
        constraints = [models.UniqueConstraint(fields=["title"], name="unique_title")]

    def __str__(self) -> str:
        return self.title

    @property
    def getMemberIDs(self):
        return [t.id for t in self.members.all()]

    def get_absolute_url(self):
        return reverse("board-index", args=[str(self.id)])

    # TODO
    # def save()


class Section(models.Model):
    title = models.CharField(max_length=MAX_TITLE_LEN, blank=False, null=False)
    description = models.TextField(blank=True, null=False)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    # TODO: add card_limit field
    # === non-editable ===
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    # dependent on the Card's completed field
    completed = models.BooleanField(default=False, editable=False)
    # we set this manually on the server based using a section value sent to the server
    section_order = models.PositiveIntegerField(
        default=0, editable=False, db_index=True
    )

    class Meta:
        ordering = ["section_order"]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        # This updates the date time field as well
        if self.board:
            self.board.save()


class Tag(models.Model):
    title = models.CharField(max_length=MAX_TITLE_LEN, blank=False, null=False)
    description = models.TextField(blank=True, null=False)
    # TODO: add color field
    board = models.ForeignKey(Board, on_delete=models.CASCADE)

    class Meta:
        # check for the same board, same title should not possible
        constraints = [
            models.UniqueConstraint(
                fields=["title", "board"], name="unique_title_board"
            )
        ]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        # This updates the date time field as well
        if self.board:
            self.board.save()


class Card(models.Model):
    class Priority(models.IntegerChoices):
        HIGH = 1, "High"
        MEDIUM = 2, "Medium"
        LOW = 3, "Low"

    priority = models.IntegerField(choices=Priority.choices, default=Priority.MEDIUM)
    title = models.CharField(max_length=MAX_TITLE_LEN, blank=False, null=False)
    description = models.TextField(blank=True, null=False)
    tags = models.ManyToManyField(Tag, blank=True)
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    completed = models.BooleanField(default=False)
    deadline = models.DateField(blank=True, null=True)
    # === non-editable ===
    card_order = models.PositiveIntegerField(default=0, editable=False, db_index=True)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    # TODO: Allow for sub-task in the card

    class Meta:
        ordering = ["card_order"]

    def __str__(self):
        return f"{self.id} - {self.title}"

    @property
    def getTagIDs(self):
        return [t.id for t in self.tags.all()]

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.section:
            sec = Section.objects.get(id=self.section.id)
            if Card.objects.filter(section=sec, completed=False).count() == 0:
                print(
                    Card.objects.filter(section=sec, completed=False).count(),
                    self.section.id,
                )
                self.section.completed = True
            else:
                self.section.completed = False

            self.section.save()

MiniTrello/Board/forms.py
from django import forms
from . import models


class BoardForm(forms.ModelForm):
    class Meta:
        model = models.Board
        exclude = ("owner",)


class CardForm(forms.ModelForm):
    class Meta:
        model = models.Card
        fields = "__all__"


class SectionForm(forms.ModelForm):
    class Meta:
        model = models.Section
        fields = "__all__"
        exclude = ("card_limit",)


class TagForm(forms.ModelForm):
    class Meta:
        model = models.Tag
        fields = "__all__"

MiniTrello/Board/views.py
# == General imports ==
import json
from datetime import datetime
from os import path

# == Django imports ==
from django.http import HttpResponse, HttpResponseNotFound
from django.conf import settings
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied

from . import models
from . import utils
from . import forms
from User.models import CustomUser

# ========= Board ===========


# https://stackoverflow.com/a/69655415
# Allow only board owner and members to view and update it content
def verify_user(view_func):
    def wrapper_func(request, *args, **kwargs):
        board = models.Board.objects.get(id=kwargs["board_id"])
        if board.owner.id == request.user.id or request.user.is_superuser:
            return view_func(request, *args, **kwargs)
        elif request.user in board.members.all():
            return view_func(request, *args, **kwargs)
        else:
            raise PermissionDenied

    return wrapper_func


@login_required(login_url="user-login")
def boardList(request):
    my_boards = models.Board.objects.filter(owner=request.user)
    member_boards = models.Board.objects.filter(members=request.user)
    context = {"my_boards": my_boards, "member_boards": member_boards}
    return render(request, template_name="Board/board_list.html", context=context)


@login_required(login_url="user-login")
def createBoard(request):
    form = forms.BoardForm()
    context = {}
    members = CustomUser.objects.all().exclude(id=request.user.id)
    context["members"] = members
    if request.method == "POST":
        form = forms.BoardForm(request.POST)
        if form.is_valid():
            board = form.save(commit=False)
            board.owner = request.user
            board.save()
            return redirect("board-list")

    context["form"] = form
    return render(request, template_name="Board/add_board.html", context=context)


@login_required(login_url="user-login")
@verify_user
def updateBoard(request, board_id):
    board = models.Board.objects.get(id=board_id)
    # allow only board owner to update
    if board.owner.id != request.user.id and not request.user.is_superuser:
        raise PermissionDenied
    form = forms.BoardForm(instance=board)
    members = CustomUser.objects.all().exclude(id=request.user.id)
    context = {
        "board": board,
        "members": members,
    }

    if request.method == "POST":
        form = forms.BoardForm(request.POST, instance=board)
        if form.is_valid():
            form.save()
            return redirect("board-list")

    context["form"] = form
    return render(request, template_name="Board/update_board.html", context=context)


@login_required(login_url="user-login")
@verify_user
def deleteBoard(request, board_id):
    board = models.Board.objects.get(id=board_id)
    # allow only board owner to delete
    if board.owner.id != request.user.id and not request.user.is_superuser:
        raise PermissionDenied
    board = models.Board.objects.get(id=board_id)
    if request.method == "POST":
        board.delete()
        return redirect("board-list")
    return render(request, template_name="Board/delete_board.html")


# ========= End Board ===========

# ========= Section ===========


@login_required(login_url="user-login")
@verify_user
def boardIndex(request, board_id):
    sections = models.Section.objects.filter(board=board_id)
    tags = models.Tag.objects.filter(board=board_id)
    context = {"sections": sections, "tags": tags, "board_id": board_id}
    return render(request, template_name="Board/index.html", context=context)


@login_required(login_url="user-login")
@verify_user
def createSection(request, board_id):
    form = forms.SectionForm()
    context = {"board_id": board_id}
    if request.method == "POST":
        form = forms.SectionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("board-index", board_id)

    context["form"] = form
    return render(request, template_name="Board/add_section.html", context=context)


@login_required(login_url="user-login")
@verify_user
def updateSection(request, board_id, section_id):
    section = models.Section.objects.get(id=section_id, board=board_id)
    form = forms.SectionForm(instance=section)
    context = {
        "section": section,
        "board_id": board_id,
    }

    if request.method == "POST":
        form = forms.SectionForm(request.POST, instance=section)
        if form.is_valid():
            form.save()
            return redirect("board-index", board_id)

    context["form"] = form
    return render(request, template_name="Board/update_section.html", context=context)


@login_required(login_url="user-login")
@verify_user
def deleteSection(request, board_id, section_id):
    section = models.Section.objects.get(id=section_id, board=board_id)
    context = {"board_id": board_id}
    if request.method == "POST":
        section.delete()
        return redirect("board-index", board_id)
    return render(request, template_name="Board/delete.html", context=context)


# ========= End Section ===========

# ========= Card ===========


@login_required(login_url="user-login")
@verify_user
def createCard(request, board_id, section_id):
    form = forms.CardForm()
    tags = models.Tag.objects.filter(board=board_id)
    priority_choices = models.Card._meta.get_field("priority").choices
    sections = models.Section.objects.filter(board=board_id)
    context = {
        "sections": sections,
        "tags": tags,
        "priority_choices": priority_choices,
        "section_id": section_id,
        "board_id": board_id,
    }

    if request.method == "POST":
        form = forms.CardForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("board-index", board_id)

    context["form"] = form
    return render(request, template_name="Board/add_card.html", context=context)


@login_required(login_url="user-login")
@verify_user
def updateCard(request, board_id, card_id):
    card = models.Card.objects.get(id=card_id)
    if card.section.board.id != board_id:
        raise PermissionDenied
    form = forms.CardForm(instance=card)
    tags = models.Tag.objects.filter(board=board_id)
    priority_choices = models.Card._meta.get_field("priority").choices
    sections = models.Section.objects.filter(board=board_id)
    context = {
        "sections": sections,
        "tags": tags,
        "priority_choices": priority_choices,
        "card": card,
        "board_id": board_id,
    }

    if request.method == "POST":
        form = forms.CardForm(request.POST, instance=card)
        if form.is_valid():
            form.save()
            return redirect("board-index", board_id)

    context["form"] = form
    return render(request, template_name="Board/update_card.html", context=context)


@login_required(login_url="user-login")
@verify_user
def deleteCard(request, board_id, card_id):
    card = models.Card.objects.get(id=card_id)
    if card.section.board.id != board_id:
        raise PermissionDenied
    context = {"board_id": board_id}
    if request.method == "POST":
        card.delete()
        return redirect("board-index", board_id)
    return render(request, template_name="Board/delete.html", context=context)


# ========= End Card ===========

# ========= Tag  ===========


@login_required(login_url="user-login")
@verify_user
def tagList(request, board_id):
    tags = models.Tag.objects.filter(board=board_id)
    context = {"tags": tags, "board_id": board_id}
    return render(request, template_name="Board/tags_list.html", context=context)


@login_required(login_url="user-login")
@verify_user
def createTag(request, board_id):
    form = forms.TagForm()
    context = {"board_id": board_id}
    if request.method == "POST":
        form = forms.TagForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("board-index", board_id)

    context["form"] = form
    return render(request, template_name="Board/add_tag.html", context=context)


@login_required(login_url="user-login")
@verify_user
def deleteTag(request, board_id, tag_id):
    tag = models.Tag.objects.get(id=tag_id, board=board_id)
    context = {"board_id": board_id}
    if request.method == "POST":
        tag.delete()
        return redirect("board-index", board_id)
    return render(request, template_name="Board/delete.html", context=context)


# ========= End Card ===========


def populateDB(request):
    if not settings.DEBUG:
        return HttpResponseNotFound
    CustomUser.objects.create_user(
        username="test1",
        password="test@abc",
        email="test1@user.com",
        first_name="Test1",
        last_name="Ln",
    )
    CustomUser.objects.create_user(
        username="test2",
        password="test@abc",
        email="test2@user.com",
        first_name="Test2",
        last_name="Ln",
    )
    CustomUser.objects.create_user(
        username="test3",
        password="test@abc",
        email="test3@user.com",
        first_name="Test3",
        last_name="Ln",
    )
    CustomUser.objects.create_user(
        username="test4",
        password="test@abc",
        email="test4@user.com",
        first_name="Test4",
        last_name="Ln",
    )
    json_file = path.abspath("../fixtures/board.json")
    utils.generate_data(json_file)
    file = open(json_file)
    json_object = json.load(file)
    if not models.Board.objects.all().exists():
        for data in json_object["Board"]:
            data["owner"] = CustomUser.objects.get(id=data["owner"])
            models.Board.objects.create(**data)

    if not models.Section.objects.all().exists():
        for data in json_object["Section"]:
            data["board"] = models.Board.objects.get(id=data["board"])
            models.Section.objects.create(**data)

MiniTrello/Board/templates/Board/add_card.html
{% extends 'base.html' %}
<!-- -->
{% block body %}
<!-- -->
{% include 'profile_navbar.html' %}
<!--  -->

<div id="add-card">
  <div class="fixed h-full w-full bg-black opacity-70 inset-0 z-0"></div>
  <div class="absolute inset-0 min-h-[100vh] min-v-[100vh] flex justify-center">
    <div class="self-center card overflow-y-auto bg-base-100 shadow-xl p-3 w-[70%]">
      <div class="card-body">
        <div class="card-actions justify-between">
          <a href="{% url 'board-index' board_id %}">
            <svg class="self-center h-10 w-10 stroke-green-400 hover:stroke-green-600 hover:cursor-pointer" xmlns="http://www.w3.org/2000/svg" stroke-width="1.12" viewBox="0 0 32 32">
              <path
                d="M14.389 7.956v4.374l1.056.01c7.335.071 11.466 3.333 12.543 9.944-4.029-4.661-8.675-4.663-12.532-4.664h-1.067v4.337l-9.884-7.001 9.884-7zm1.067-2.063L2.661 14.956l12.795 9.063v-5.332c5.121.002 9.869.26 13.884 7.42 0-4.547-.751-14.706-13.884-14.833V5.893z"
              />
            </svg>
          </a>
          <div class="text-3xl font-bold self-center">Card Details</div>
          <button type="submit" form="create_card_form" value="Submit" class="btn btn-primary bg-green-200 hover:bg-green-300 hover:shadow-lg">Submit</button>
        </div>
        <div class="divider divider-neutral p-0 m-0"></div>
        {% if form.errors %}
        <!--  -->
        <div>{{form.errors}}</div>
        <!--  -->
        {% endif%}
        <form class="p-5 grid grid-cols-5 gap-4" action="" method="post" id="create_card_form">
          {% csrf_token %}
          <!--  -->
          <!--  -->
          <label class="col-span-1 self-center text-xl font-semibold text-right" for="id_priority">Priority:</label>
          <select class="col-span-4 select select-bordered w-full max-w-xs text-xl" name="priority" id="id_priority" required>
            <option disabled selected>Whats the Priority</option>
            {% for value, label in priority_choices %}
            <!--  -->
            {%if value == 2 %}
            <option value="{{value}}" selected>{{label}}</option>
            {% else %}
            <!--  -->
            <option value="{{value}}">{{label}}</option>
            {% endif %}
            <!--  -->
            {% endfor %}
          </select>
          <!--  -->
          <label class="col-span-1 self-center text-xl font-semibold text-right" for="id_title">Title:</label>
          <input class="col-span-4 input input-bordered w-full max-w-xs text-xl" type="text" name="title" maxlength="64" id="id_title" required />
          <!--  -->
          <label class="col-span-1 self-center text-xl font-semibold text-right" for="id_description">Description:</label>
          <textarea class="col-span-4 text-xl textarea textarea-bordered" name="description" id="id_description"> </textarea>
          <!--  -->
          <label class="col-span-1 self-center text-xl font-semibold text-right" for="id_tags">Tags:</label>
          <select class="col-span-4 select select-bordered w-full max-w-xs text-xl p-2" name="tags" id="id_tags" multiple>
            {% for tag in tags %}
            <option v-multi-select value="{{tag.id}}">{{tag.title}}</option>
            {% endfor %}
          </select>
          <!-- -->
          <label class="col-span-1 self-center text-xl font-semibold text-right" for="id_section">Section:</label>
          <select class="col-span-4 select select-bordered w-full max-w-xs text-xl" name="section" id="id_section" required>
            {% for section in sections %}
            <!--  -->
            {%if section_id == section.id %}
            <option value="{{section.id}}" selected>Section {{section.id}}</option>
            {% else %}
            <!--  -->
            <option value="{{section.id}}">Section {{section.id}}</option>
            {% endif %}
            <!--  -->
            {% endfor %}
          </select>
          <!-- -->
          <!--  -->
          <label class="col-span-1 self-center text-xl font-semibold text-right" for="id_completed">Completed:</label>
          <input class="col-span-4 checkbox" type="checkbox" name="completed" id="id_completed" />
          <!--  -->
          <label class="col-span-1 self-center text-xl font-semibold text-right" for="dp-input-id_deadline">Deadline:</label>
          <Datepicker
            name="deadline"
            uid="id_deadline"
            class="col-span-1 self-center text-xl font-semibold text-right"
            v-model="date"
            :enable-time-picker="false"
            :month-change-on-scroll="false"
            :format="dateFormat"
            auto-apply
          />
        </form>
      </div>
    </div>
  </div>
</div>
<script type="module">
  const { createApp } = Vue;

  const app = createApp({
    data() {
      return {
        date: "",
        dateFormat: (date) => {
          const day = date.getDate();
          const month = date.getMonth() + 1;
          const year = date.getFullYear();
          return `${year}-${month}-${day}`;
        },
      };
    },
    components: { Datepicker: VueDatePicker },
  });
  // app.directive("click-outside", {
  //   beforeMount: function (element, binding, vnode) {
  //     element.click_outside = function (event) {
  //       if (!(element == event.target || element.contains(event.target))) {
  //         binding.value();
  //       }
  //     };
  //     document.body.addEventListener("click", element.click_outside);
  //   },
  //   unmounted: function (element) {
  //     document.body.removeEventListener("click", element.click_outside);
  //   },
  // });
  app.directive("multi-select", {
    mounted: function (element, binding, vnode) {
      // https://codepen.io/wripcode/pen/ZEvMOEL
      const parent = element.parentElement;
      element.multi_select = function (element) {
        element.preventDefault();
        var originalScrollTop = parent.scrollTop;
        this.selected = !this.selected;
        parent.focus();
        setTimeout(function () {
          parent.scrollTop = originalScrollTop;
        }, 0);
      };
      element.addEventListener("mousedown", element.multi_select, false);
    },
    unmounted: function (element) {
      element.removeEventListener("mousedown", element.multi_select, false);
    },
  });
  app.config.compilerOptions.delimiters = ["[[", "]]"];
  app.mount("#add-card");
</script>

{% endblock body %}

MiniTrello/Board/templates/Board/delete.html
{% extends 'base.html' %}
<!-- -->
{% block body %}
<!-- -->
{% include 'profile_navbar.html' %}
<!--  -->

<div id="delete-card-section">
  <div class="fixed h-full w-full bg-black opacity-70 inset-0 z-0"></div>
  <div class="absolute inset-0 min-h-[100vh] min-v-[100vh] flex justify-center">
    <div class="self-center card overflow-y-auto bg-base-100 shadow-xl p-3 w-[70%]">
      <div class="card">
        <div class="card-body items-center text-center">
          <h2 class="card-title text-3xl">Are You Sure ??</h2>
          <div class="divider divider-neutral p-0 m-0"></div>
          <form action="" method="post" id="delete_card_section_form">
            {% csrf_token %}
            <!--  -->
            <div class="card-actions justify-end">
              <button type="submit" form="delete_card_section_form" value="Submit" class="btn btn-ghost border-black text-xl">Delete</button>
              <a href="{% url 'board-index' board_id %}" class="btn btn-ghost border-black text-xl">Back</a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock body %}

MiniTrello/Board/templates/Board/update_card.html
{% extends 'base.html' %}
<!--  -->
{% block body %}
<!-- -->
{% include 'profile_navbar.html' %}
<!--  -->

<div id="update-card">
  <div class="fixed h-full w-full bg-black opacity-70 inset-0 z-0"></div>
  <div class="absolute inset-0 min-h-[100vh] min-v-[100vh] flex justify-center">
    <div class="self-center card overflow-y-auto bg-base-100 shadow-xl p-3 w-[70%]">
      <div class="card-body">
        <div class="card-actions justify-between">
          <a href="{% url 'board-index' board_id %}">
            <svg class="self-center h-10 w-10 stroke-green-400 hover:stroke-green-600 hover:cursor-pointer" xmlns="http://www.w3.org/2000/svg" stroke-width="1.12" viewBox="0 0 32 32">
              <path
                d="M14.389 7.956v4.374l1.056.01c7.335.071 11.466 3.333 12.543 9.944-4.029-4.661-8.675-4.663-12.532-4.664h-1.067v4.337l-9.884-7.001 9.884-7zm1.067-2.063L2.661 14.956l12.795 9.063v-5.332c5.121.002 9.869.26 13.884 7.42 0-4.547-.751-14.706-13.884-14.833V5.893z"
              />
            </svg>
          </a>
          <div class="text-3xl font-bold self-center">Card Details</div>
          <button type="submit" form="update_card_form" value="Submit" class="btn btn-primary bg-green-200 hover:bg-green-300 hover:shadow-lg">Submit</button>
        </div>
        <div class="divider divider-neutral p-0 m-0"></div>
        {% if form.errors %}
        <!--  -->
        <div>{{form.errors}}</div>
        <!--  -->
        {% endif%}
        <form class="p-5 grid grid-cols-5 gap-4" action="" method="post" id="update_card_form">
          {% csrf_token %}
          <!--  -->
          <!--  -->
          <label class="col-span-1 self-center text-xl font-semibold text-right" for="id_priority">Priority:</label>
          <select class="col-span-4 select select-bordered w-full max-w-xs text-xl" name="priority" id="id_priority" required>
            <option disabled selected>Whats the Priority</option>
            {% for value, label in priority_choices %}
            <!--  -->
            {%if value == card.priority %}
            <option value="{{value}}" selected>{{label}}</option>
            {% else %}
            <option value="{{value}}">{{label}}</option>
            {% endif %}
            <!--  -->
            {% endfor %}
          </select>
          <!--  -->
          <label class="col-span-1 self-center text-xl font-semibold text-right" for="id_title">Title:</label>
          <input class="col-span-4 input input-bordered w-full max-w-xs text-xl" type="text" value="{{card.title}}" name="title" maxlength="64" id="id_title" />
          <!--  -->
          <label class="col-span-1 self-center text-xl font-semibold text-right" for="id_description">Description:</label>
          <textarea class="col-span-4 text-xl textarea textarea-bordered" value="{{card.description}}" name="description" id="id_description">{{card.description}}</textarea>
          <!--  -->
          <label class="col-span-1 self-center text-xl font-semibold text-right" for="id_tags">Tags:</label>
          <select class="col-span-4 select select-bordered w-full max-w-xs text-xl p-2" name="tags" id="id_tags" multiple>
            {% for tag in tags %}
            <!--  -->
            {%if tag.id in card.getTagIDs %}
            <option v-multi-select value="{{tag.id}}" selected>{{tag.title}}</option>
            {% else %}
            <option v-multi-select value="{{tag.id}}">{{tag.title}}</option>
            {% endif %}
            <!--  -->
            {% endfor %}
          </select>
          <!--  -->
          <label class="col-span-1 self-center text-xl font-semibold text-right" for="id_section">Section:</label>
          <input class="col-span-4 input input-bordered w-full max-w-xs text-xl hover:cursor-not-allowed" type="text" name="section" id="id_section" value="{{card.section.id}}" readonly />
          <!--  -->
          <label class="col-span-1 self-center text-xl font-semibold text-right" for="id_completed">Completed:</label>
          <!--  -->
          {%if card.completed %}
          <input class="col-span-4 checkbox" type="checkbox" name="completed" id="id_completed" checked />
          {% else %}
          <input class="col-span-4 checkbox" type="checkbox" name="completed" id="id_completed" />
          {% endif %}
          <!--  -->
          <label class="col-span-1 self-center text-xl font-semibold text-right" for="dp-input-id_deadline">Deadline:</label>
          <Datepicker
            name="deadline"
            uid="id_deadline"
            class="col-span-1 self-center text-xl font-semibold text-right"
            v-model="date"
            :enable-time-picker="false"
            :month-change-on-scroll="false"
            :format="dateFormat"
            auto-apply
          />
        </form>
      </div>
    </div>
  </div>
</div>
<script type="module">
  const { createApp } = Vue;

  const app = createApp({
    data() {
      return {
        date: "{{card.deadline}}",
        dateFormat: (date) => {
          const day = date.getDate();
          const month = date.getMonth() + 1;
          const year = date.getFullYear();
          return `${year}-${month}-${day}`;
        },
      };
    },

    components: { Datepicker: VueDatePicker },
  });
  // app.directive("click-outside", {
  //   beforeMount: function (element, binding, vnode) {
  //     element.click_outside = function (event) {
  //       if (!(element == event.target || element.contains(event.target))) {
  //         binding.value();
  //       }
  //     };
  //     document.body.addEventListener("click", element.click_outside);
  //   },
  //   unmounted: function (element) {
  //     document.body.removeEventListener("click", element.click_outside);
  //   },
  // });
  app.directive("multi-select", {
    mounted: function (element, binding, vnode) {
      // https://codepen.io/wripcode/pen/ZEvMOEL
      const parent = element.parentElement;
      element.multi_select = function (element) {
        element.preventDefault();
        var originalScrollTop = parent.scrollTop;
        this.selected = !this.selected;
        parent.focus();
        setTimeout(function () {
          parent.scrollTop = originalScrollTop;
        }, 0);
      };
      element.addEventListener("mousedown", element.multi_select, false);
    },
    unmounted: function (element) {
      element.removeEventListener("mousedown", element.multi_select, false);
    },
  });
  app.config.compilerOptions.delimiters = ["[[", "]]"];
  app.mount("#update-card");
</script>

{% endblock body %}